name: Stress Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  stess-test:
    name: Stress Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stress-test:
          - simple_echo_tcp
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - uses: Swatinem/rust-cache@v1
      - name: Install Valgrind
        run: |
          sudo apt-get update -qq
          # libc6-dbg is needed to run Valgrind
          sudo apt-get install -y libc6-dbg
          # Use snap to install the latest Valgrind
          # https://snapcraft.io/install/valgrind/ubuntu
          sudo snap install valgrind --classic

      # Compiles each of the stress test examples.
      - name: Compile stress test examples
        run: cargo build -p stress-test --release --example ${{ matrix.stress-test }}

      # Runs each of the examples using Valgrind. Detects leaks and displays them.
      - name: Run valgrind
        run: valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./target/release/examples/${{ matrix.stress-test }}
